local log = require("log.log")

local evolved = require("decore.evolved")
local fragments = require("decore.fragments")
local entities = require("entity.entities")
local systems = require("system.systems")

---@class scene.game
---@field systems evolved.id[]
---@field systems_fixed evolved.id[]


---@param self scene.game
function init(self)
	log:info("Game Script Init")
	self.systems = systems.get_systems()

	evolved.clone(entities["game_gui"])
	evolved.clone(entities["level1"])
end


function update(self, dt)
	evolved.set(fragments.dt, fragments.dt, dt)
	evolved.process(unpack(self.systems))
end
