local decore = require("decore.decore")
local systems = require("system.systems")
local entities = require("entity.entities")

---@class scene.game
---@field world world

---@param self scene.game
function init(self)
	self.world = decore.world(systems.get_systems())
	decore.register_entities("game", entities.get_entities())
	decore.print_loaded_packs_debug_info()
	decore.print_loaded_systems_debug_info(self.world)

	self.world:refresh()

	self.world.command_flow_game:start_flow()
end


---@param self scene.game
function final(self)
	decore.final(self.world)
end


---@param self scene.game
---@param dt number
function update(self, dt)
	self.world:update(dt)
end


---@param self scene.game
---@param action_id hash
---@param action table
function on_input(self, action_id, action)
	return decore.on_input(self.world, action_id, action)
end
