#!/bin/bash
# lhttps://github.com/Insality/defold-deployer

# You can point bob version for project in format "filename:sha"
bob_sha=":e4aaff11f49c941fde1dd93883cf69c6b8abebe4"

# Select Defold channel. Values: stable, beta, alpha
bob_channel="beta"

# If true, it will check and download latest bob version. It will ignore bob_sha param
use_latest_bob=true

# Select Defold build server
build_server="https://build.defold.com"

# Pre-build hook bash script path. The path relative from game project folder
pre_build_script=false

# Post-build hook bash script path. The path relative from game project folder
post_build_script=false

# Set patch (last value after dot) game version value as total git commits count (1.2.0 -> 1.2.{commits_count})
# You allow to get SHA commit from version via: git rev-list --all --reverse | sed -n {N}p
enable_incremental_version=true

# Use git commits count as android.version_code on build
enable_incremental_android_version_code=true

# Local resource cache folder for deployer script. This folder will be added to gitignore if exists
resource_cache_local=".cache_deployer"

# Exclude folders from build
exclude_folders="server"
