version: '3'
services:
  cockroachdb:
    image: cockroachdb/cockroach:latest-v20.2
    command: start-single-node --insecure --store=attrs=ssd,path=/var/lib/cockroach/
    restart: "no"
    volumes:
      - data:/var/lib/cockroach
    expose:
      - "8080"
      - "26257"
    ports:
      - "26257:26257"
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: 3s
      timeout: 3s
      retries: 5
  nakama:
    image: registry.heroiclabs.com/heroiclabs/nakama:3.16.0
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
        /nakama/nakama migrate up --database.address "root@cockroachdb:26257" &&
        exec /nakama/nakama --name Template --database.address "root@cockroachdb:26257" \
                            --logger.level DEBUG --session.token_expiry_sec 10800 \
                            --socket.server_key SERVER_KER_HERE --runtime.http_key HTTP_KEY_HERE \
                            --session.encryption_key ENCRYPTION_KEY_HERE --session.refresh_encryption_key REFRESH_KEY_HERE \
                            --console.username USERNAME --console.password PASSWORD --console.port 7569 \
                            --console.signing_key SIGN_KEY --matchmaker.interval_sec 10 --shutdown_grace_sec 360
    restart: "no"
    volumes:
      - ./:/nakama/data
      - ../game/shared:/nakama/data/modules/game/shared
      - ../game/const.lua:/nakama/data/modules/game/const.lua
    links:
      - "cockroachdb:db"
    depends_on:
      cockroachdb:
        condition: service_healthy
    expose:
      - "7349"
      - "7350"
      - "7569"
      - "9100"
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7569:7569"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7350/"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  data:
