local druid = require("druid.druid")
local gui_menu = require("entity.gui_menu.gui_menu")

function init(self)
	self.druid = druid.new(self)
	self.widget = self.druid:new_widget(gui_menu, "gui_menu")
end

function final(self)
	self.druid:final()
end

function update(self, dt)
	self.druid:update(dt)
end

function on_message(self, message_id, message, sender)
	self.druid:on_message(message_id, message, sender)
end

function on_input(self, action_id, action)
	return self.druid:on_input(action_id, action)
end
